services:
  app:
    container_name: flex-url-app
    restart: unless-stopped
    build: .
    volumes:
      - .:/var/www:cached
      - /var/www/vendor
      - /var/www/node_modules
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    working_dir: /var/www
    networks:
      - shared-dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mysql:
    image: mysql:8.0.35
    container_name: flex-url-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - shared-dev
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  nginx:
    image: nginx:1.25-alpine
    container_name: flex-url-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:80"
    volumes:
      - ./public:/var/www/public:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - shared-dev
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    container_name: flex-url-phpmyadmin
    restart: unless-stopped
    ports:
      - "${PMA_PORT:-8080}:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - shared-dev
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

networks:
  shared-dev:
    external: true
    
volumes:
  mysql_data:
